services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.multi
    image: spam-api:multi
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: cache
    depends_on:
      - cache

  cache:
    image: redis:7-alpine
