FROM python:3.11 AS builder

WORKDIR /build

COPY requirements.txt .

RUN pip install --no-cache-dir --prefix=/install -r requirements.txt


FROM python:3.11-slim AS runner

WORKDIR /app

COPY --from=builder /install /usr/local

COPY app ./app
COPY data/spam_model.joblib ./data/spam_model.joblib

EXPOSE 8080

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
